name: Hello World Action
description: A Hello World Action
inputs:
  who:  #input id
    description: 'who to say hallo world'
    required: true
    default: 'world'
output:
  date: #output id
    description: 'the time that the command runned'
runs:
  using: 'Docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.who }}
